from __future__ import annotations

EMAIL_PROVIDER_SMTP = "smtp"
EMAIL_PROVIDER_SENDGRID = "sendgrid"
SMS_PROVIDER_AFRICAS_TALKING = "africas_talking"
SMS_PROVIDER_CELCOM = "celcom"
AFRICAS_TALKING_SANDBOX_USERNAME = "sandbox"
AFRICAS_TALKING_SANDBOX_BASE_URL = "https://api.sandbox.africastalking.com/version1/messaging"
AFRICAS_TALKING_LIVE_BASE_URL = "https://api.africastalking.com/version1/messaging"
CELCOM_SMS_BASE_URL = "https://isms.celcomafrica.com/api/services/sendsms/"

STORAGE_PROVIDER_LOCAL = "local"
STORAGE_PROVIDER_SUPABASE = "supabase"

OAUTH_PROVIDER_GOOGLE = "google"

SUPPORTED_EMAIL_PROVIDERS = {
    EMAIL_PROVIDER_SMTP,
    EMAIL_PROVIDER_SENDGRID,
}

SUPPORTED_SMS_PROVIDERS = {
    SMS_PROVIDER_AFRICAS_TALKING,
    SMS_PROVIDER_CELCOM,
}

SUPPORTED_STORAGE_PROVIDERS = {
    STORAGE_PROVIDER_LOCAL,
    STORAGE_PROVIDER_SUPABASE,
}

SUPPORTED_OAUTH_PROVIDERS = {
    OAUTH_PROVIDER_GOOGLE,
}

DEFAULT_EMAIL_PROVIDER = EMAIL_PROVIDER_SMTP
DEFAULT_SMS_PROVIDER = SMS_PROVIDER_AFRICAS_TALKING
DEFAULT_STORAGE_PROVIDER = STORAGE_PROVIDER_LOCAL
DEFAULT_SUPABASE_TIMEOUT = 30
DEFAULT_SIGNED_URL_TTL = 300
