from __future__ import annotations

EMAIL_PROVIDER_SMTP = "smtp"
EMAIL_PROVIDER_SENDGRID = "sendgrid"

STORAGE_PROVIDER_LOCAL = "local"
STORAGE_PROVIDER_SUPABASE = "supabase"

OAUTH_PROVIDER_GOOGLE = "google"

SUPPORTED_EMAIL_PROVIDERS = {
    EMAIL_PROVIDER_SMTP,
    EMAIL_PROVIDER_SENDGRID,
}

SUPPORTED_STORAGE_PROVIDERS = {
    STORAGE_PROVIDER_LOCAL,
    STORAGE_PROVIDER_SUPABASE,
}

SUPPORTED_OAUTH_PROVIDERS = {
    OAUTH_PROVIDER_GOOGLE,
}

DEFAULT_EMAIL_PROVIDER = EMAIL_PROVIDER_SMTP
DEFAULT_STORAGE_PROVIDER = STORAGE_PROVIDER_LOCAL
DEFAULT_SUPABASE_TIMEOUT = 30
DEFAULT_SIGNED_URL_TTL = 300
