app = "worknest-backend"
primary_region = "nbo"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "config.settings.production"
  ENVIRONMENT = "production"
  APP_SERVER = "gunicorn"
  RUN_MIGRATIONS = "1"
  RUN_COLLECTSTATIC = "1"
  SMS_ENABLED = "false"
  SMS_PROVIDER = "africas_talking"
  AFRICAS_TALKING_USE_SANDBOX = "true"
  AFRICAS_TALKING_USERNAME = "sandbox"
  AFRICAS_TALKING_ENVIRONMENT = "sandbox"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "30s"
    method = "get"
    path = "/api/v1/health/ready/"
