# Generated by Django 4.2.9 on 2026-04-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='custom_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
