# Generated by Codex on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task Assigned"),
                    ("deadline_approaching", "Deadline Approaching"),
                    ("comment_posted", "Comment Posted"),
                    ("mentioned_in_comment", "Mentioned In Comment"),
                    ("team_invite", "Team Invite"),
                    ("invitation_accepted", "Invitation Accepted"),
                    ("invitation_declined", "Invitation Declined"),
                    ("admin_message", "Admin Message"),
                    ("team_announcement", "Team Announcement"),
                ],
                max_length=40,
            ),
        ),
    ]
