# Generated by Django 4.2.9 on 2026-04-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_admin_communications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admincommunication',
            new_name='admin_commu_audienc_c522c2_idx',
            old_name='admin_commun_audien_4d02be_idx',
        ),
        migrations.RenameIndex(
            model_name='admincommunication',
            new_name='admin_commu_channel_a41166_idx',
            old_name='admin_commun_channe_95d93c_idx',
        ),
        migrations.RenameIndex(
            model_name='admincommunication',
            new_name='admin_commu_status_15f0f8_idx',
            old_name='admin_commun_status_6fa795_idx',
        ),
        migrations.RenameIndex(
            model_name='admincommunicationrecipient',
            new_name='admin_commu_communi_536f2e_idx',
            old_name='admin_commu_commun_f2b4a4_idx',
        ),
        migrations.RenameIndex(
            model_name='admincommunicationrecipient',
            new_name='admin_commu_user_id_637494_idx',
            old_name='admin_commu_user_id_3f2e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='admincommunicationrecipient',
            new_name='admin_commu_team_id_685bcc_idx',
            old_name='admin_commu_team_id_678b99_idx',
        ),
    ]
