# Generated by Django 4.2.9 on 2026-04-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_smsdelivery'),
        ('notifications', '0007_notification_is_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincommunication',
            name='delivered_sms_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admincommunication',
            name='failed_sms_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admincommunicationrecipient',
            name='sms_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_communication_recipients', to='integrations.smsdelivery'),
        ),
        migrations.AddField(
            model_name='admincommunicationrecipient',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admincommunication',
            name='channel_type',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('email_and_in_app', 'Email + In-App'), ('sms_and_in_app', 'SMS + In-App'), ('email_and_sms', 'Email + SMS'), ('all', 'In-App + Email + SMS')], max_length=24),
        ),
        migrations.AlterField(
            model_name='admincommunication',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('partial_failure', 'Partial Failure'), ('failed', 'Failed')], default='sent', max_length=16),
        ),
        migrations.AlterField(
            model_name='admincommunicationrecipient',
            name='channel_type',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('email_and_in_app', 'Email + In-App'), ('sms_and_in_app', 'SMS + In-App'), ('email_and_sms', 'Email + SMS'), ('all', 'In-App + Email + SMS')], max_length=24),
        ),
    ]
