# Generated by Django 4.2.9 on 2026-04-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='allow_manager_invites',
            field=models.BooleanField(default=False),
        ),
    ]
