# Generated by Django 4.2.9 on 2026-04-07 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0002_team_allow_manager_invites"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamAnnouncement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("pinned_until", models.DateTimeField(blank=True, null=True)),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="published_announcements", to=settings.AUTH_USER_MODEL)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="announcements", to="teams.team")),
            ],
            options={
                "db_table": "team_announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteTeam",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pinned_by", to="teams.team")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorite_teams", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "favorite_teams",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RecentTeamVisit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_accessed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recent_visits", to="teams.team")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recent_team_visits", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "recent_team_visits",
                "ordering": ["-last_accessed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="teamannouncement",
            index=models.Index(fields=["team", "is_active"], name="team_announ_team_id_f71e62_idx"),
        ),
        migrations.AddIndex(
            model_name="teamannouncement",
            index=models.Index(fields=["team", "created_at"], name="team_announ_team_id_67237c_idx"),
        ),
        migrations.AddIndex(
            model_name="favoriteteam",
            index=models.Index(fields=["user", "updated_at"], name="favorite_te_user_id_20f49c_idx"),
        ),
        migrations.AddConstraint(
            model_name="favoriteteam",
            constraint=models.UniqueConstraint(fields=("user", "team"), name="unique_favorite_team"),
        ),
        migrations.AddIndex(
            model_name="recentteamvisit",
            index=models.Index(fields=["user", "last_accessed_at"], name="recent_team_user_id_bf7fb3_idx"),
        ),
        migrations.AddConstraint(
            model_name="recentteamvisit",
            constraint=models.UniqueConstraint(fields=("user", "team"), name="unique_recent_team_visit"),
        ),
    ]
