# Generated by Django 4.2.9 on 2026-04-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamannouncement_favoriteteam_recentteamvisit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favoriteteam',
            new_name='favorite_te_user_id_4e8b19_idx',
            old_name='favorite_te_user_id_20f49c_idx',
        ),
        migrations.RenameIndex(
            model_name='recentteamvisit',
            new_name='recent_team_user_id_dbaaf7_idx',
            old_name='recent_team_user_id_bf7fb3_idx',
        ),
        migrations.RenameIndex(
            model_name='teamannouncement',
            new_name='team_announ_team_id_5c8030_idx',
            old_name='team_announ_team_id_f71e62_idx',
        ),
        migrations.RenameIndex(
            model_name='teamannouncement',
            new_name='team_announ_team_id_9f725a_idx',
            old_name='team_announ_team_id_67237c_idx',
        ),
    ]
