# Generated by Django 4.2.9 on 2026-04-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_rename_favorite_te_user_id_20f49c_idx_favorite_te_user_id_4e8b19_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
