# Generated by Django 4.2.9 on 2026-04-08 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0005_team_is_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamannouncement',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamannouncement',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamannouncement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='teamannouncement',
            index=models.Index(fields=['team', 'expires_at'], name='team_announ_team_id_ee3bb1_idx'),
        ),
    ]
