# Generated by Django 4.2.9 on 2026-04-08 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_onboarding_primary_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                ('token', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'push_devices',
                'ordering': ['-last_seen_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='security_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('ready', 'Ready'), ('enabled', 'Enabled')], default='disabled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified', 'created_at'], name='users_email_v_0e1649_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['theme_preference'], name='users_theme_p_52f53c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_seen_at'], name='users_last_se_547346_idx'),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['user', 'is_active'], name='push_device_user_id_8c34d3_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['platform', 'is_active'], name='push_device_platfor_425de5_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['last_seen_at'], name='push_device_last_se_a5707c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushdevice',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='unique_user_push_token'),
        ),
    ]
