# Generated by Django 4.2.9 on 2026-04-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pushdevice_user_last_seen_at_user_last_seen_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('google', 'Google')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_verified', 'created_at'], name='users_phone_v_586dce_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['sms_opt_in', 'created_at'], name='users_sms_opt_e65113_idx'),
        ),
    ]
