# Generated by Django 4.2.9 on 2026-04-07 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[
                    ("user_registered", "User Registered"),
                    ("user_logged_in", "User Logged In"),
                    ("user_logged_out", "User Logged Out"),
                    ("user_login_failed", "User Login Failed"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("password_reset_confirmed", "Password Reset Confirmed"),
                    ("google_login_requested", "Google Login Requested"),
                    ("team_created", "Team Created"),
                    ("team_updated", "Team Updated"),
                    ("team_archived", "Team Archived"),
                    ("team_deleted", "Team Deleted"),
                    ("member_invited", "Member Invited"),
                    ("invitation_accepted", "Invitation Accepted"),
                    ("invitation_declined", "Invitation Declined"),
                    ("member_role_changed", "Member Role Changed"),
                    ("member_removed", "Member Removed"),
                    ("task_created", "Task Created"),
                    ("task_updated", "Task Updated"),
                    ("task_assigned", "Task Assigned"),
                    ("task_status_changed", "Task Status Changed"),
                    ("task_archived", "Task Archived"),
                    ("task_deleted", "Task Deleted"),
                    ("comment_created", "Comment Created"),
                    ("comment_updated", "Comment Updated"),
                    ("comment_deleted", "Comment Deleted"),
                    ("attachment_uploaded", "Attachment Uploaded"),
                    ("attachment_deleted", "Attachment Deleted"),
                    ("notification_marked_read", "Notification Marked Read"),
                    ("notification_marked_unread", "Notification Marked Unread"),
                    ("notifications_marked_read", "Notifications Marked Read"),
                    ("notification_deleted", "Notification Deleted"),
                ], max_length=64)),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("target_repr", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_logs", to=settings.AUTH_USER_MODEL)),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_logs", to="teams.team")),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["actor", "created_at"], name="audit_logs_actor_i_8b4fc9_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action", "created_at"], name="audit_logs_action__8b9499_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["team", "created_at"], name="audit_logs_team_id_c0d676_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["target_type", "target_id"], name="audit_logs_target__b7d794_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["created_at"], name="audit_logs_created_78a2d4_idx"),
        ),
    ]
