# Generated by Codex on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0003_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("user_registered", "User Registered"),
                    ("user_logged_in", "User Logged In"),
                    ("user_logged_out", "User Logged Out"),
                    ("user_login_failed", "User Login Failed"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("password_reset_confirmed", "Password Reset Confirmed"),
                    ("google_login_requested", "Google Login Requested"),
                    ("account_linked", "Account Linked"),
                    ("team_created", "Team Created"),
                    ("team_updated", "Team Updated"),
                    ("team_archived", "Team Archived"),
                    ("team_deleted", "Team Deleted"),
                    ("member_invited", "Member Invited"),
                    ("invitation_resent", "Invitation Resent"),
                    ("invitation_revoked", "Invitation Revoked"),
                    ("invitation_accepted", "Invitation Accepted"),
                    ("invitation_declined", "Invitation Declined"),
                    ("invitation_role_updated", "Invitation Role Updated"),
                    ("member_role_changed", "Member Role Changed"),
                    ("member_removed", "Member Removed"),
                    ("task_created", "Task Created"),
                    ("task_updated", "Task Updated"),
                    ("task_assigned", "Task Assigned"),
                    ("task_status_changed", "Task Status Changed"),
                    ("task_archived", "Task Archived"),
                    ("task_deleted", "Task Deleted"),
                    ("task_label_created", "Task Label Created"),
                    ("task_label_attached", "Task Label Attached"),
                    ("task_label_detached", "Task Label Detached"),
                    ("task_checklist_created", "Task Checklist Created"),
                    ("task_checklist_updated", "Task Checklist Updated"),
                    ("task_checklist_deleted", "Task Checklist Deleted"),
                    ("task_watcher_added", "Task Watcher Added"),
                    ("task_watcher_removed", "Task Watcher Removed"),
                    ("task_bulk_updated", "Task Bulk Updated"),
                    ("task_favorited", "Task Favorited"),
                    ("task_unfavorited", "Task Unfavorited"),
                    ("comment_created", "Comment Created"),
                    ("comment_updated", "Comment Updated"),
                    ("comment_deleted", "Comment Deleted"),
                    ("attachment_uploaded", "Attachment Uploaded"),
                    ("attachment_deleted", "Attachment Deleted"),
                    ("email_queued", "Email Queued"),
                    ("email_sent", "Email Sent"),
                    ("email_failed", "Email Failed"),
                    ("email_skipped", "Email Skipped"),
                    ("notification_marked_read", "Notification Marked Read"),
                    ("notification_marked_unread", "Notification Marked Unread"),
                    ("notifications_marked_read", "Notifications Marked Read"),
                    ("notification_deleted", "Notification Deleted"),
                    ("admin_notification_sent", "Admin Notification Sent"),
                    ("team_announcement_created", "Team Announcement Created"),
                    ("team_announcement_updated", "Team Announcement Updated"),
                    ("team_pinned", "Team Pinned"),
                    ("team_unpinned", "Team Unpinned"),
                ],
                max_length=64,
            ),
        ),
    ]
