# Generated by Django 4.2.9 on 2026-04-07 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comments", "0003_remove_attachment_model_state"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Attachment",
                    fields=[
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("file", models.FileField(upload_to="attachments/%Y/%m/")),
                        ("filename", models.CharField(max_length=255)),
                        ("file_size", models.PositiveIntegerField()),
                        ("mime_type", models.CharField(max_length=100)),
                        ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                        (
                            "task",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="attachments",
                                to="tasks.task",
                            ),
                        ),
                        (
                            "uploaded_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="uploaded_attachments",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "attachments",
                        "ordering": ["-created_at"],
                    },
                ),
            ],
        ),
    ]
