# Generated by Django 4.2.9 on 2026-04-07 00:00

from pathlib import Path

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


def backfill_attachment_fields(apps, schema_editor):
    Attachment = apps.get_model("attachments", "Attachment")
    api_version = getattr(settings, "API_VERSION", "v1")

    for attachment in Attachment.objects.all().iterator():
        attachment.file_name = attachment.file_name or Path(attachment.file_path).name
        attachment.file_url = attachment.file_url or f"/api/{api_version}/attachments/{attachment.pk}/download/"
        update_fields = ["file_name", "file_url", "updated_at"]
        attachment.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment",
            old_name="file",
            new_name="file_path",
        ),
        migrations.RenameField(
            model_name="attachment",
            old_name="filename",
            new_name="original_name",
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file_path",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file_size",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="mime_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="attachment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="file_name",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="file_url",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attachment",
            name="storage_provider",
            field=models.CharField(
                choices=[("local", "Local"), ("supabase", "Supabase")],
                default="local",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_attachment_fields, noop_reverse),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["task", "is_deleted"], name="attachments_task_id_b86312_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["created_at"], name="attachments_created_31fc5e_idx"),
        ),
    ]
