# Generated by Django 4.2.9 on 2026-04-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_rework_attachment_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_task_id_47a2f9_idx',
            old_name='attachments_task_id_b86312_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_created_d487af_idx',
            old_name='attachments_created_31fc5e_idx',
        ),
    ]
