from django.urls import path

from apps.tasks.views import (
    AutomationRuleDetailView,
    AutomationRuleListCreateView,
    FavoriteTaskListView,
    FavoriteTaskToggleView,
    GuestTaskAccessDetailView,
    GuestTaskAccessListCreateView,
    GuestTaskAccessRevokeView,
    GuestTaskCommentCreateView,
    MilestoneDetailView,
    MilestoneListCreateView,
    MyTasksView,
    OverdueTasksView,
    RecentTaskListView,
    SavedTaskViewListCreateView,
    SavedTaskViewDetailView,
    TaskDependencyDetailView,
    TaskDependencyListCreateView,
    TaskArchiveView,
    TaskAssignView,
    TaskBoardView,
    TaskBulkActionView,
    TaskChecklistDetailView,
    TaskChecklistListCreateView,
    TaskDetailView,
    TaskLabelListCreateView,
    TaskListCreateView,
    TaskTimelineView,
    TaskTemplateInstantiateView,
    TaskTemplateListCreateView,
    TaskStatusView,
    TaskImportView,
    TaskExportView,
    TimeEntryListCreateView,
    TimeEntryStartView,
    TimeEntryStopView,
    TimeEntrySummaryView,
    TaskWatcherView,
)

app_name = "tasks"

urlpatterns = [
    path("", TaskListCreateView.as_view(), name="list-create"),
    path("labels/", TaskLabelListCreateView.as_view(), name="labels"),
    path("templates/", TaskTemplateListCreateView.as_view(), name="templates"),
    path("templates/<uuid:pk>/create-task/", TaskTemplateInstantiateView.as_view(), name="template-create-task"),
    path("views/saved/", SavedTaskViewListCreateView.as_view(), name="saved-views"),
    path("views/saved/<uuid:view_id>/", SavedTaskViewDetailView.as_view(), name="saved-view-detail"),
    path("dependencies/<uuid:dependency_id>/", TaskDependencyDetailView.as_view(), name="dependency-detail"),
    path("import/", TaskImportView.as_view(), name="import"),
    path("export/", TaskExportView.as_view(), name="export"),
    path("time-entries/summary/", TimeEntrySummaryView.as_view(), name="time-summary"),
    path("bulk/", TaskBulkActionView.as_view(), name="bulk-action"),
    path("favorites/", FavoriteTaskListView.as_view(), name="favorites"),
    path("recent/", RecentTaskListView.as_view(), name="recent"),
    path("checklist/<uuid:checklist_id>/", TaskChecklistDetailView.as_view(), name="checklist-detail"),
    path("guest/<str:token>/", GuestTaskAccessDetailView.as_view(), name="guest-detail"),
    path("guest/<str:token>/comments/", GuestTaskCommentCreateView.as_view(), name="guest-comment"),
    path("<uuid:pk>/", TaskDetailView.as_view(), name="detail"),
    path("<uuid:pk>/status/", TaskStatusView.as_view(), name="status"),
    path("<uuid:pk>/assign/", TaskAssignView.as_view(), name="assign"),
    path("<uuid:pk>/archive/", TaskArchiveView.as_view(), name="archive"),
    path("<uuid:pk>/checklist/", TaskChecklistListCreateView.as_view(), name="checklist"),
    path("<uuid:pk>/dependencies/", TaskDependencyListCreateView.as_view(), name="dependencies"),
    path("<uuid:pk>/guest-access/", GuestTaskAccessListCreateView.as_view(), name="guest-access"),
    path("guest-access/<uuid:access_id>/revoke/", GuestTaskAccessRevokeView.as_view(), name="guest-revoke"),
    path("<uuid:pk>/time-entries/", TimeEntryListCreateView.as_view(), name="time-entries"),
    path("<uuid:pk>/time-entries/start/", TimeEntryStartView.as_view(), name="time-start"),
    path("time-entries/<uuid:entry_id>/stop/", TimeEntryStopView.as_view(), name="time-stop"),
    path("<uuid:pk>/watchers/", TaskWatcherView.as_view(), name="watchers"),
    path("<uuid:pk>/timeline/", TaskTimelineView.as_view(), name="timeline"),
    path("<uuid:pk>/favorite/", FavoriteTaskToggleView.as_view(), name="favorite-toggle"),
    path("my-tasks/", MyTasksView.as_view(), name="my-tasks"),
    path("board/", TaskBoardView.as_view(), name="board"),
    path("overdue/", OverdueTasksView.as_view(), name="overdue"),
    path("teams/<uuid:team_id>/milestones/", MilestoneListCreateView.as_view(), name="milestones"),
    path("teams/<uuid:team_id>/milestones/<uuid:milestone_id>/", MilestoneDetailView.as_view(), name="milestone-detail"),
    path("teams/<uuid:team_id>/automation-rules/", AutomationRuleListCreateView.as_view(), name="automation-rules"),
    path("teams/<uuid:team_id>/automation-rules/<uuid:rule_id>/", AutomationRuleDetailView.as_view(), name="automation-rule-detail"),
]
