# Generated by Django 4.2.9 on 2026-04-08 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_emailverificationtoken_authsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phone_verification_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='phone_verif_user_id_e9ab20_idx'), models.Index(fields=['phone_number', 'expires_at'], name='phone_verif_phone_n_705ae6_idx'), models.Index(fields=['used_at', 'expires_at'], name='phone_verif_used_at_1989e3_idx')],
            },
        ),
    ]
