# Generated by Django 4.2.9 on 2026-04-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_credentialchangerequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='credentialchangerequest',
            new_name='credential__user_id_b6f46d_idx',
            old_name='credentialc_user_id_d8827a_idx',
        ),
        migrations.RenameIndex(
            model_name='credentialchangerequest',
            new_name='credential__new_val_cd81b2_idx',
            old_name='credentialc_new_val_6256f6_idx',
        ),
        migrations.RenameIndex(
            model_name='credentialchangerequest',
            new_name='credential__current_757346_idx',
            old_name='credentialc_current_67725d_idx',
        ),
    ]
