from __future__ import annotations

from apps.realtime.constants import (
    COMMENT_CREATED_EVENT,
    COMMENT_DELETED_EVENT,
    COMMENT_UPDATED_EVENT,
    NOTIFICATION_CREATED_EVENT,
    NOTIFICATION_DELETED_EVENT,
    NOTIFICATION_UNREAD_COUNT_EVENT,
    NOTIFICATION_UPDATED_EVENT,
    SYSTEM_PONG_EVENT,
    TASK_ARCHIVED_EVENT,
    TASK_ASSIGNED_EVENT,
    TASK_CREATED_EVENT,
    TASK_DELETED_EVENT,
    TASK_STATUS_CHANGED_EVENT,
    TASK_UPDATED_EVENT,
    TEAM_INVITE_RECEIVED_EVENT,
)

USER_SCOPED_EVENTS = {
    NOTIFICATION_CREATED_EVENT,
    NOTIFICATION_UPDATED_EVENT,
    NOTIFICATION_DELETED_EVENT,
    NOTIFICATION_UNREAD_COUNT_EVENT,
    TASK_ASSIGNED_EVENT,
    TEAM_INVITE_RECEIVED_EVENT,
    SYSTEM_PONG_EVENT,
}

TEAM_SCOPED_EVENTS = {
    TASK_CREATED_EVENT,
    TASK_UPDATED_EVENT,
    TASK_STATUS_CHANGED_EVENT,
    TASK_ASSIGNED_EVENT,
    TASK_ARCHIVED_EVENT,
    TASK_DELETED_EVENT,
    COMMENT_CREATED_EVENT,
    COMMENT_UPDATED_EVENT,
    COMMENT_DELETED_EVENT,
}

ALL_REALTIME_EVENTS = USER_SCOPED_EVENTS | TEAM_SCOPED_EVENTS


def build_event_message(*, event_name: str, data: dict) -> dict:
    return {
        "type": event_name,
        "event": event_name,
        "data": data,
    }
