<?php

return [
    'roles' => [
        'owner' => [
            'create_team',
            'edit_team',
            'delete_team',
            'invite_member',
            'remove_member',
            'create_task',
            'edit_task',
            'delete_task',
            'assign_task',
            'comment_task',
            'upload_attachment',
            'manage_notifications',
            'export_reports',
            'view_audit_logs',
            'manage_settings',
        ],
        'admin' => [
            'create_team',
            'edit_team',
            'invite_member',
            'remove_member',
            'create_task',
            'edit_task',
            'delete_task',
            'assign_task',
            'comment_task',
            'upload_attachment',
            'manage_notifications',
            'export_reports',
            'view_audit_logs',
        ],
        'member' => [
            'create_task',
            'edit_task',
            'comment_task',
            'upload_attachment',
            'manage_notifications',
        ],
    ],
    'team_roles' => [
        'team_owner' => [
            'edit_team',
            'delete_team',
            'invite_member',
            'remove_member',
            'create_task',
            'edit_task',
            'delete_task',
            'assign_task',
            'comment_task',
            'upload_attachment',
            'manage_notifications',
            'export_reports',
            'view_audit_logs',
            'manage_team_settings',
        ],
        'team_admin' => [
            'invite_member',
            'remove_member',
            'create_task',
            'edit_task',
            'delete_task',
            'assign_task',
            'comment_task',
            'upload_attachment',
            'manage_notifications',
            'export_reports',
            'view_audit_logs',
        ],
        'team_member' => [
            'create_task',
            'edit_task',
            'comment_task',
            'upload_attachment',
            'manage_notifications',
        ],
        'guest' => [
            'view_task',
            'view_comment',
        ],
    ],
];