# Generated by Django 4.2.9 on 2026-04-07 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0002_team_allow_manager_invites"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=20)),
                ("estimated_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("planned_offset_days", models.PositiveIntegerField(blank=True, null=True)),
                ("due_offset_days", models.PositiveIntegerField(blank=True, null=True)),
                ("blocked_reason", models.CharField(blank=True, max_length=255)),
                ("recurrence_pattern", models.CharField(choices=[("none", "Does Not Repeat"), ("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")], default="none", max_length=20)),
                ("recurrence_interval", models.PositiveIntegerField(default=1)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="task_templates_assigned", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_task_templates", to=settings.AUTH_USER_MODEL)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_templates", to="teams.team")),
            ],
            options={
                "db_table": "task_templates",
                "ordering": ["name", "-created_at"],
                "unique_together": {("team", "name")},
            },
        ),
        migrations.CreateModel(
            name="SavedTaskView",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("layout", models.CharField(choices=[("list", "List"), ("kanban", "Kanban"), ("calendar", "Calendar"), ("workload", "Workload")], default="list", max_length=20)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saved_task_views", to="teams.team")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_task_views", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "saved_task_views",
                "ordering": ["name", "-updated_at"],
                "unique_together": {("user", "team", "name")},
            },
        ),
        migrations.AddField(
            model_name="task",
            name="blocked_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="is_recurring_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="task",
            name="planned_for_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_interval",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_pattern",
            field=models.CharField(choices=[("none", "Does Not Repeat"), ("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")], default="none", max_length=20),
        ),
        migrations.AddField(
            model_name="task",
            name="source_template",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="generated_tasks", to="tasks.tasktemplate"),
        ),
        migrations.AddIndex(
            model_name="tasktemplate",
            index=models.Index(fields=["team", "name"], name="task_templa_team_id_465cab_idx"),
        ),
        migrations.AddIndex(
            model_name="tasktemplate",
            index=models.Index(fields=["team", "created_at"], name="task_templa_team_id_097b8f_idx"),
        ),
        migrations.AddIndex(
            model_name="savedtaskview",
            index=models.Index(fields=["user", "layout"], name="saved_task__user_id_dc619b_idx"),
        ),
        migrations.AddIndex(
            model_name="savedtaskview",
            index=models.Index(fields=["team", "layout"], name="saved_task__team_id_5a77ee_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["team", "planned_for_date"], name="tasks_team_id_e70cf0_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["team", "recurrence_pattern"], name="tasks_team_id_547a20_idx"),
        ),
    ]
