# Generated by Django 4.2.9 on 2026-04-07 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0002_team_allow_manager_invites"),
        ("tasks", "0002_tasktemplate_savedtaskview_task_modern_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLabel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                ("color", models.CharField(default="#10b981", max_length=16)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_task_labels", to=settings.AUTH_USER_MODEL)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_labels", to="teams.team")),
            ],
            options={
                "db_table": "task_labels",
                "ordering": ["name", "-created_at"],
                "unique_together": {("team", "name")},
            },
        ),
        migrations.CreateModel(
            name="TaskChecklistItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="completed_checklist_items", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_checklist_items", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checklist_items", to="tasks.task")),
            ],
            options={
                "db_table": "task_checklist_items",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskWatcher",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="watchers", to="tasks.task")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="watched_tasks", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "task_watchers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorited_by", to="tasks.task")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorite_tasks", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "favorite_tasks",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RecentTaskVisit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_accessed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recent_visits", to="tasks.task")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recent_task_visits", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "recent_task_visits",
                "ordering": ["-last_accessed_at"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(blank=True, related_name="tasks", to="tasks.tasklabel"),
        ),
        migrations.AddIndex(
            model_name="tasklabel",
            index=models.Index(fields=["team", "name"], name="task_labels_team_id_3124f8_idx"),
        ),
        migrations.AddIndex(
            model_name="taskchecklistitem",
            index=models.Index(fields=["task", "position"], name="task_checkl_task_id_5958fd_idx"),
        ),
        migrations.AddIndex(
            model_name="taskchecklistitem",
            index=models.Index(fields=["task", "is_completed"], name="task_checkl_task_id_c2ce62_idx"),
        ),
        migrations.AddIndex(
            model_name="taskwatcher",
            index=models.Index(fields=["user", "created_at"], name="task_watche_user_id_7746f9_idx"),
        ),
        migrations.AddConstraint(
            model_name="taskwatcher",
            constraint=models.UniqueConstraint(fields=("task", "user"), name="unique_task_watcher"),
        ),
        migrations.AddIndex(
            model_name="favoritetask",
            index=models.Index(fields=["user", "updated_at"], name="favorite_ta_user_id_8e35ce_idx"),
        ),
        migrations.AddConstraint(
            model_name="favoritetask",
            constraint=models.UniqueConstraint(fields=("user", "task"), name="unique_favorite_task"),
        ),
        migrations.AddIndex(
            model_name="recenttaskvisit",
            index=models.Index(fields=["user", "last_accessed_at"], name="recent_task_user_id_c0f499_idx"),
        ),
        migrations.AddConstraint(
            model_name="recenttaskvisit",
            constraint=models.UniqueConstraint(fields=("user", "task"), name="unique_recent_task_visit"),
        ),
    ]
