# Generated by Django 4.2.9 on 2026-04-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasklabel_taskchecklistitem_taskwatcher_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favoritetask',
            new_name='favorite_ta_user_id_6e02c0_idx',
            old_name='favorite_ta_user_id_8e35ce_idx',
        ),
        migrations.RenameIndex(
            model_name='recenttaskvisit',
            new_name='recent_task_user_id_14339d_idx',
            old_name='recent_task_user_id_c0f499_idx',
        ),
        migrations.RenameIndex(
            model_name='savedtaskview',
            new_name='saved_task__user_id_1f36fb_idx',
            old_name='saved_task__user_id_dc619b_idx',
        ),
        migrations.RenameIndex(
            model_name='savedtaskview',
            new_name='saved_task__team_id_2cf45f_idx',
            old_name='saved_task__team_id_5a77ee_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_team_id_698aa6_idx',
            old_name='tasks_team_id_e70cf0_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_team_id_d99e13_idx',
            old_name='tasks_team_id_547a20_idx',
        ),
        migrations.RenameIndex(
            model_name='taskchecklistitem',
            new_name='task_checkl_task_id_ef7dec_idx',
            old_name='task_checkl_task_id_5958fd_idx',
        ),
        migrations.RenameIndex(
            model_name='taskchecklistitem',
            new_name='task_checkl_task_id_72003d_idx',
            old_name='task_checkl_task_id_c2ce62_idx',
        ),
        migrations.RenameIndex(
            model_name='tasklabel',
            new_name='task_labels_team_id_dedbac_idx',
            old_name='task_labels_team_id_3124f8_idx',
        ),
        migrations.RenameIndex(
            model_name='tasktemplate',
            new_name='task_templa_team_id_6b276d_idx',
            old_name='task_templa_team_id_465cab_idx',
        ),
        migrations.RenameIndex(
            model_name='tasktemplate',
            new_name='task_templa_team_id_4213b1_idx',
            old_name='task_templa_team_id_097b8f_idx',
        ),
        migrations.RenameIndex(
            model_name='taskwatcher',
            new_name='task_watche_user_id_f5295c_idx',
            old_name='task_watche_user_id_7746f9_idx',
        ),
    ]
