# Generated by Django 4.2.9 on 2026-04-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_favorite_ta_user_id_8e35ce_idx_favorite_ta_user_id_6e02c0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
