# Generated by Django 4.2.9 on 2026-04-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_savedtaskview_shared_pinned'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='automationrule',
            new_name='automation__team_id_383003_idx',
            old_name='automation_rule_team_trigger_active_idx',
        ),
        migrations.RenameIndex(
            model_name='guesttaskaccess',
            new_name='guest_task__task_id_9bbd91_idx',
            old_name='guest_task_access_task_created_idx',
        ),
        migrations.RenameIndex(
            model_name='guesttaskaccess',
            new_name='guest_task__email_a046c1_idx',
            old_name='guest_task_access_email_created_idx',
        ),
        migrations.RenameIndex(
            model_name='milestone',
            new_name='milestones_team_id_b9cd87_idx',
            old_name='milestones_team_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='milestone',
            new_name='milestones_team_id_649b23_idx',
            old_name='milestones_team_id_due_date_idx',
        ),
        migrations.RenameIndex(
            model_name='savedtaskview',
            new_name='saved_task__user_id_cef476_idx',
            old_name='saved_task_user_is_pinned_idx',
        ),
        migrations.RenameIndex(
            model_name='savedtaskview',
            new_name='saved_task__team_id_855e26_idx',
            old_name='saved_task_team_is_pinned_idx',
        ),
        migrations.RenameIndex(
            model_name='taskdependency',
            new_name='task_depend_from_ta_3ebb18_idx',
            old_name='task_depend_from_task_dep_type_idx',
        ),
        migrations.RenameIndex(
            model_name='taskdependency',
            new_name='task_depend_to_task_31490b_idx',
            old_name='task_depend_to_task_dep_type_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='time_entrie_task_id_bc2d82_idx',
            old_name='time_entries_task_start_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='time_entrie_user_id_766f71_idx',
            old_name='time_entries_user_start_idx',
        ),
    ]
