# Generated by Django 4.2.9 on 2026-04-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_rename_automation_rule_team_trigger_active_idx_automation__team_id_383003_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationrule",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("create_notification", "Create Notification"),
                    ("send_email", "Send Email"),
                    ("assign_user", "Assign User"),
                    ("change_status", "Change Status"),
                    ("add_label", "Add Label"),
                    ("create_follow_up_task", "Create Follow-up Task"),
                    ("notify_admin", "Notify Admin"),
                ],
                max_length=40,
            ),
        ),
    ]
