# Generated by Django 4.2.9 on 2026-04-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='email_deliv_status_44280d_idx',
            old_name='email_deliv_status_17e4f0_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='email_deliv_email_t_e9b19f_idx',
            old_name='email_deliv_email_t_fb9145_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='email_deliv_recipie_76a17e_idx',
            old_name='email_deliv_recipie_7e6656_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='email_deliv_dedupe__46c53d_idx',
            old_name='email_deliv_dedupe__e3874e_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='email_deliv_related_e60aec_idx',
            old_name='email_deliv_related_bf7f77_idx',
        ),
    ]
