# Generated by Django 4.2.9 on 2026-04-08 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0002_rename_email_deliv_status_17e4f0_idx_email_deliv_status_44280d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('message_type', models.CharField(max_length=64)),
                ('message_body', models.CharField(max_length=640)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('dedupe_key', models.CharField(blank=True, max_length=255)),
                ('related_object_type', models.CharField(blank=True, max_length=64)),
                ('related_object_id', models.CharField(blank=True, max_length=64)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sms_deliver_status_8e47b8_idx'), models.Index(fields=['message_type', 'created_at'], name='sms_deliver_message_837ed9_idx'), models.Index(fields=['phone_number', 'created_at'], name='sms_deliver_phone_n_37286e_idx'), models.Index(fields=['user', 'created_at'], name='sms_deliver_user_id_effca5_idx'), models.Index(fields=['dedupe_key'], name='sms_deliver_dedupe__3c6ab6_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='sms_deliver_related_44e056_idx')],
            },
        ),
    ]
