# Generated by Django 4.2.9 on 2026-04-09 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0009_alter_automationrule_action_type"),
        ("teams", "0006_teamannouncement_archived_at_and_more"),
        ("integrations", "0003_smsdelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(default="google", max_length=32)),
                ("scope", models.CharField(choices=[("personal", "Personal"), ("team", "Team")], default="personal", max_length=16)),
                ("status", models.CharField(choices=[("connected", "Connected"), ("disconnected", "Disconnected"), ("error", "Error")], default="disconnected", max_length=24)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("external_calendar_id", models.CharField(blank=True, max_length=255)),
                ("external_calendar_name", models.CharField(blank=True, max_length=255)),
                ("sync_direction", models.CharField(choices=[("app_to_google", "App to Google"), ("two_way", "Two-way")], default="app_to_google", max_length=24)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="calendar_connections", to="teams.team")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_connections", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "calendar_connections",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["user", "scope", "status"], name="calendar_co_user_id_171718_idx"),
                    models.Index(fields=["team", "scope", "status"], name="calendar_co_team_id_908fd5_idx"),
                    models.Index(fields=["provider", "status"], name="calendar_co_provider_923821_idx"),
                    models.Index(fields=["updated_at"], name="calendar_co_updated_a257b4_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "team", "provider", "scope"), name="unique_calendar_connection_scope"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CalendarImportBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope", models.CharField(choices=[("personal", "Personal"), ("team", "Team")], default="personal", max_length=16)),
                ("source", models.CharField(choices=[("ics", "ICS"), ("google", "Google")], default="ics", max_length=16)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="calendar_import_batches", to="teams.team")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_import_batches", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "calendar_import_batches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "expires_at"], name="calendar_im_user_id_f66ca3_idx"),
                    models.Index(fields=["team", "expires_at"], name="calendar_im_team_id_2a7a11_idx"),
                    models.Index(fields=["scope", "source"], name="calendar_im_scope_26f654_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CalendarEventBinding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_event_id", models.CharField(max_length=255)),
                ("external_calendar_id", models.CharField(blank=True, max_length=255)),
                ("etag", models.CharField(blank=True, max_length=255)),
                ("sync_status", models.CharField(choices=[("synced", "Synced"), ("failed", "Failed"), ("deleted", "Deleted")], default="synced", max_length=20)),
                ("last_synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_bindings", to="integrations.calendarconnection")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_bindings", to="tasks.task")),
            ],
            options={
                "db_table": "calendar_event_bindings",
                "ordering": ["-last_synced_at"],
                "indexes": [
                    models.Index(fields=["connection", "sync_status"], name="calendar_ev_connecti_4f96f4_idx"),
                    models.Index(fields=["task", "sync_status"], name="calendar_ev_task_id_8c4870_idx"),
                    models.Index(fields=["last_synced_at"], name="calendar_ev_last_sy_b2f7d3_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("connection", "task"), name="unique_calendar_binding_task"),
                    models.UniqueConstraint(fields=("connection", "external_event_id"), name="unique_calendar_binding_external_event"),
                ],
            },
        ),
    ]
