# Generated by Django 4.2.9 on 2026-04-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_calendarconnection_calendarimportbatch_calendareventbinding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarconnection',
            new_name='calendar_co_user_id_7b83cd_idx',
            old_name='calendar_co_user_id_171718_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarconnection',
            new_name='calendar_co_team_id_ccbe52_idx',
            old_name='calendar_co_team_id_908fd5_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarconnection',
            new_name='calendar_co_provide_47a613_idx',
            old_name='calendar_co_provider_923821_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarconnection',
            new_name='calendar_co_updated_5ca533_idx',
            old_name='calendar_co_updated_a257b4_idx',
        ),
        migrations.RenameIndex(
            model_name='calendareventbinding',
            new_name='calendar_ev_connect_bc21da_idx',
            old_name='calendar_ev_connecti_4f96f4_idx',
        ),
        migrations.RenameIndex(
            model_name='calendareventbinding',
            new_name='calendar_ev_task_id_941635_idx',
            old_name='calendar_ev_task_id_8c4870_idx',
        ),
        migrations.RenameIndex(
            model_name='calendareventbinding',
            new_name='calendar_ev_last_sy_b57849_idx',
            old_name='calendar_ev_last_sy_b2f7d3_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarimportbatch',
            new_name='calendar_im_user_id_2e3cf1_idx',
            old_name='calendar_im_user_id_f66ca3_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarimportbatch',
            new_name='calendar_im_team_id_0f40d5_idx',
            old_name='calendar_im_team_id_2a7a11_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarimportbatch',
            new_name='calendar_im_scope_326e70_idx',
            old_name='calendar_im_scope_26f654_idx',
        ),
    ]
