services:
  - type: web
    name: worknest-backend
    env: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    healthCheckPath: /api/v1/health/live/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: ENVIRONMENT
        value: production
      - key: APP_SERVER
        value: gunicorn
      - key: RUN_MIGRATIONS
        value: "1"
      - key: RUN_COLLECTSTATIC
        value: "1"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PUBLIC_WEBAPP_URL
        value: https://worknested.netlify.app
      - key: BACKEND_URL
        sync: false
      - key: INVITE_LINK_BASE_URL
        sync: false
      - key: PASSWORD_RESET_LINK_BASE_URL
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: EMAIL_FROM_NAME
        value: WorkNest
      - key: EMAIL_PROVIDER
        value: smtp
      - key: EMAIL_DELIVERY_MODE
        value: sync
      - key: SMS_ENABLED
        value: "false"
      - key: SMS_PROVIDER
        value: africas_talking
      - key: AFRICAS_TALKING_USE_SANDBOX
        value: "true"
      - key: AFRICAS_TALKING_USERNAME
        value: sandbox
      - key: AFRICAS_TALKING_API_KEY
        sync: false
      - key: AFRICAS_TALKING_SENDER_ID
        sync: false
      - key: AFRICAS_TALKING_ENVIRONMENT
        value: sandbox
      - key: AFRICAS_TALKING_BASE_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: ADMIN_BOOTSTRAP_ENABLED
        value: "0"
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_NAME
        value: WorkNest Admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: ATTACHMENTS_STORAGE_BACKEND
        value: supabase
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: ATTACHMENTS_SUPABASE_BUCKET
        sync: false
      - key: ATTACHMENTS_SIGNED_URL_TTL
        value: "300"
      - key: APP_NAME
        value: WorkNest
      - key: SUPPORT_EMAIL
        sync: false
      - key: LOGO_URL
        sync: false
      - key: AUTH_COOKIE_SECURE
        value: "True"
      - key: AUTH_COOKIE_SAMESITE
        value: "None"
