# Generated by Django 4.2.9 on 2026-04-07 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_comment_edited_at_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="Attachment",
                ),
            ],
        ),
    ]
