# Generated by Django 4.2.9 on 2026-04-07 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_remove_attachment_model_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(choices=[('👍', 'Thumbs Up'), ('❤️', 'Heart'), ('🎉', 'Celebrate'), ('👀', 'Eyes'), ('🔥', 'Fire')], max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_reactions',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['comment', 'emoji'], name='comment_rea_comment_af813a_idx'), models.Index(fields=['user', 'created_at'], name='comment_rea_user_id_f54a31_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(fields=('comment', 'user', 'emoji'), name='unique_comment_user_emoji_reaction'),
        ),
    ]
