# Generated by Django 4.2.9 on 2026-04-08 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0004_commentreaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='comments.comment')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_versions',
                'ordering': ['-edited_at', '-created_at'],
                'indexes': [models.Index(fields=['comment', 'edited_at'], name='comment_ver_comment_335d26_idx')],
            },
        ),
    ]
