# Generated by Django 4.2.9 on 2026-04-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_guest_fields'),
        ('comments', '0005_commentversion'),
    ]

    operations = [
    ]
